package temporary;

import java.util.Date;

public class CourseStudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.id
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.created_at
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.updated_at
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.course_id
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.student_id
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.id
     *
     * @return the value of course_student.id
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.id
     *
     * @param id the value for course_student.id
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.created_at
     *
     * @return the value of course_student.created_at
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.created_at
     *
     * @param createdAt the value for course_student.created_at
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.updated_at
     *
     * @return the value of course_student.updated_at
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.updated_at
     *
     * @param updatedAt the value for course_student.updated_at
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.course_id
     *
     * @return the value of course_student.course_id
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.course_id
     *
     * @param courseId the value for course_student.course_id
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.student_id
     *
     * @return the value of course_student.student_id
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.student_id
     *
     * @param studentId the value for course_student.student_id
     *
     * @mbg.generated Thu Mar 05 19:05:32 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}
