package temporary;

import java.util.Date;

public class RecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.id
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.created_at
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.updated_at
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.course_id
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private Integer courseId;

    private String atDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.time
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private String atTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.outline
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private String outline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.feedback
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private String feedback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.next_outline
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private String nextOutline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.requirement
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private String requirement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.homework
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private String homework;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.remark
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.id
     *
     * @return the value of record.id
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.id
     *
     * @param id the value for record.id
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.created_at
     *
     * @return the value of record.created_at
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.created_at
     *
     * @param createdAt the value for record.created_at
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.updated_at
     *
     * @return the value of record.updated_at
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.updated_at
     *
     * @param updatedAt the value for record.updated_at
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.course_id
     *
     * @return the value of record.course_id
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.course_id
     *
     * @param courseId the value for record.course_id
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.time
     *
     * @return the value of record.time
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public String getAtTime() {
        return atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.time
     *
     * @param atTime the value for record.time
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setAtTime(String atTime) {
        this.atTime = atTime == null ? null : atTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.outline
     *
     * @return the value of record.outline
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public String getOutline() {
        return outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.outline
     *
     * @param outline the value for record.outline
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setOutline(String outline) {
        this.outline = outline == null ? null : outline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.feedback
     *
     * @return the value of record.feedback
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.feedback
     *
     * @param feedback the value for record.feedback
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.next_outline
     *
     * @return the value of record.next_outline
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public String getNextOutline() {
        return nextOutline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.next_outline
     *
     * @param nextOutline the value for record.next_outline
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setNextOutline(String nextOutline) {
        this.nextOutline = nextOutline == null ? null : nextOutline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.requirement
     *
     * @return the value of record.requirement
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.requirement
     *
     * @param requirement the value for record.requirement
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.homework
     *
     * @return the value of record.homework
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public String getHomework() {
        return homework;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.homework
     *
     * @param homework the value for record.homework
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setHomework(String homework) {
        this.homework = homework == null ? null : homework.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.remark
     *
     * @return the value of record.remark
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.remark
     *
     * @param remark the value for record.remark
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public String getAtDate() {
        return atDate;
    }

    public void setAtDate(String atDate) {
        this.atDate = atDate == null ? null : atDate.trim();
    }
}
