package temporary;

import java.util.Date;

public class StudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.created_at
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.updated_at
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.school
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade_and_class
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String gradeAndClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.parent_name
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.telephone
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.address
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.subject
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.lesson_count
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private Integer lessonCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.registered_at
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String registeredAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.expense
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private Integer expense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.discount
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.refund
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private Integer refund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.remark
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.created_at
     *
     * @return the value of student.created_at
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.created_at
     *
     * @param createdAt the value for student.created_at
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.updated_at
     *
     * @return the value of student.updated_at
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.updated_at
     *
     * @param updatedAt the value for student.updated_at
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.school
     *
     * @return the value of student.school
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.school
     *
     * @param school the value for student.school
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade_and_class
     *
     * @return the value of student.grade_and_class
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getGradeAndClass() {
        return gradeAndClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade_and_class
     *
     * @param gradeAndClass the value for student.grade_and_class
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setGradeAndClass(String gradeAndClass) {
        this.gradeAndClass = gradeAndClass == null ? null : gradeAndClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.parent_name
     *
     * @return the value of student.parent_name
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.parent_name
     *
     * @param parentName the value for student.parent_name
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.telephone
     *
     * @return the value of student.telephone
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.telephone
     *
     * @param telephone the value for student.telephone
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.subject
     *
     * @return the value of student.subject
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.subject
     *
     * @param subject the value for student.subject
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.lesson_count
     *
     * @return the value of student.lesson_count
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public Integer getLessonCount() {
        return lessonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.lesson_count
     *
     * @param lessonCount the value for student.lesson_count
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setLessonCount(Integer lessonCount) {
        this.lessonCount = lessonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.registered_at
     *
     * @return the value of student.registered_at
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getRegisteredAt() {
        return registeredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.registered_at
     *
     * @param registeredAt the value for student.registered_at
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setRegisteredAt(String registeredAt) {
        this.registeredAt = registeredAt == null ? null : registeredAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.expense
     *
     * @return the value of student.expense
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public Integer getExpense() {
        return expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.expense
     *
     * @param expense the value for student.expense
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setExpense(Integer expense) {
        this.expense = expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.discount
     *
     * @return the value of student.discount
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.discount
     *
     * @param discount the value for student.discount
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setDiscount(String discount) {
        this.discount = discount == null ? null : discount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.refund
     *
     * @return the value of student.refund
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public Integer getRefund() {
        return refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.refund
     *
     * @param refund the value for student.refund
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setRefund(Integer refund) {
        this.refund = refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.remark
     *
     * @return the value of student.remark
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.remark
     *
     * @param remark the value for student.remark
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}
