package temporary;

import xyz.qzpx.em.dataObject.StudentDO;

import java.util.List;

public interface StudentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    StudentDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Mar 06 16:27:31 CST 2020
     */
    int updateByPrimaryKey(StudentDO record);

    List<StudentDO> selectAll();

    List<StudentDO> selectByName(String name);

    List<Integer> selectAllId();

    Integer selectCount();
}
