package temporary;

import java.util.Date;

public class TeacherDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.created_at
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.updated_at
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.gender
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.telephone
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.type
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.password
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.profession
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private String profession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.level
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.remark
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.created_at
     *
     * @return the value of teacher.created_at
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.created_at
     *
     * @param createdAt the value for teacher.created_at
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.updated_at
     *
     * @return the value of teacher.updated_at
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.updated_at
     *
     * @param updatedAt the value for teacher.updated_at
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.gender
     *
     * @return the value of teacher.gender
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.gender
     *
     * @param gender the value for teacher.gender
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.telephone
     *
     * @return the value of teacher.telephone
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.telephone
     *
     * @param telephone the value for teacher.telephone
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.type
     *
     * @return the value of teacher.type
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.type
     *
     * @param type the value for teacher.type
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.password
     *
     * @return the value of teacher.password
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.password
     *
     * @param password the value for teacher.password
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.profession
     *
     * @return the value of teacher.profession
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.profession
     *
     * @param profession the value for teacher.profession
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.level
     *
     * @return the value of teacher.level
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.level
     *
     * @param level the value for teacher.level
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.remark
     *
     * @return the value of teacher.remark
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.remark
     *
     * @param remark the value for teacher.remark
     *
     * @mbg.generated Fri Mar 20 10:53:10 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

}
