package temporary;

import xyz.qzpx.em.dataObject.TeacherDO;

import java.util.List;

public interface TeacherDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Mar 09 09:55:56 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Mar 09 09:55:56 CST 2020
     */
    int insert(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Mar 09 09:55:56 CST 2020
     */
    int insertSelective(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Mar 09 09:55:56 CST 2020
     */
    TeacherDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Mar 09 09:55:56 CST 2020
     */
    int updateByPrimaryKeySelective(TeacherDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Mon Mar 09 09:55:56 CST 2020
     */
    int updateByPrimaryKey(TeacherDO record);

    List<TeacherDO> selectAll();

    List<TeacherDO> selectByName(String name);

    List<Integer> selectAllId();

    Integer selectCount();
}
