package xyz.qzpx.em.dao;

import org.apache.ibatis.annotations.Param;
import xyz.qzpx.em.dataObject.CourseDO;

import java.util.List;

public interface CourseDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    int insert(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    int insertSelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    CourseDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    int updateByPrimaryKeySelective(CourseDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    int updateByPrimaryKey(CourseDO record);

    List<CourseDO> selectAll();

    Integer selectCount();

    List<String> selectAllType();

    List<String> selectGradeByType(String type);

    List<String> selectSubjectByTypeAndGrade(@Param("type") String type,
                                             @Param("grade") String grade);

    List<String> selectAllGrade();

    List<String> selectAllSubject();

    List<String> selectAllTerm();

    List<String> selectAllTypeByTerm(String term);

    List<String> selectGradeByTermAndType(@Param("term") String term,
                                          @Param("type") String type);

    //List<String> selectSubjectByTermAndTypeAndGrade(@Param("term") String term,
    //                                                @Param("type") String type,
    //                                                @Param("grade") String grade);

    List<CourseDO> selectSubjectByTermAndTypeAndGrade(@Param("term") String term,
                                                    @Param("type") String type,
                                                    @Param("grade") String grade);


    Integer selectId(@Param("term") String term,
                    @Param("type") String type,
                    @Param("grade") String grade,
                    @Param("subject") String subject);
}
