package xyz.qzpx.em.dao;

import xyz.qzpx.em.dataObject.LessonDO;

import java.util.List;

public interface LessonDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    int insert(LessonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    int insertSelective(LessonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    LessonDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    int updateByPrimaryKeySelective(LessonDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    int updateByPrimaryKey(LessonDO record);

    List<LessonDO> selectAll();

    Integer selectCount();
}
