package xyz.qzpx.em.dao;

import xyz.qzpx.em.dataObject.RecordDO;

import java.util.List;

public interface RecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    int insert(RecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    int insertSelective(RecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    RecordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    int updateByPrimaryKeySelective(RecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Sun Mar 22 23:19:35 CST 2020
     */
    int updateByPrimaryKey(RecordDO record);

    List<RecordDO> selectByCourseId(Integer courseId);
}
