package xyz.qzpx.em.dao;

import xyz.qzpx.em.dataObject.RoleMenuDO;

import java.util.List;

public interface RoleMenuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    int insert(RoleMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    int insertSelective(RoleMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    RoleMenuDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    int updateByPrimaryKeySelective(RoleMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_menu
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    int updateByPrimaryKey(RoleMenuDO record);

    List<RoleMenuDO> selectByRid(Integer rid);
}
