package xyz.qzpx.em.dao;

import org.apache.ibatis.annotations.Param;
import xyz.qzpx.em.dataObject.SignUpDO;

import java.util.List;

public interface SignUpDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    int insert(SignUpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    int insertSelective(SignUpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    SignUpDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    int updateByPrimaryKeySelective(SignUpDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_up
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    int updateByPrimaryKey(SignUpDO record);

    List<SignUpDO> selectByStatus(Integer status);

    List<SignUpDO> selectByStatusAndProcessor(@Param("processor") String processor,
                                              @Param("status") Integer i);

    List<SignUpDO> selectByStatusAndCreator(@Param("creator") String creator,
                                            @Param("status") Integer i);

    List<SignUpDO> selectAll();
}
