package xyz.qzpx.em.dao;

import org.apache.ibatis.annotations.Param;
import xyz.qzpx.em.dataObject.CourseStudentDO;
import xyz.qzpx.em.dataObject.SignDetailDO;
import xyz.qzpx.em.dataObject.StatisticsDO;

import java.util.List;

public interface SignDetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_detail
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_detail
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    int insert(SignDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_detail
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    int insertSelective(SignDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_detail
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    SignDetailDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_detail
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    int updateByPrimaryKeySelective(SignDetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sign_detail
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    int updateByPrimaryKey(SignDetailDO record);

    List<SignDetailDO> selectByStuId(Integer id);

    void deleteByStudentId(Integer id);

    List<Integer> selectCourseIds();

    List<Integer> selectByCourseId(Integer courseId);

    List<SignDetailDO> selectAll();

    List<StatisticsDO> selectDayData();

    List<StatisticsDO> selectWeekData();

    List<StatisticsDO> selectMonthData();

    List<StatisticsDO> selectYearData();

    List<Integer> selectStuIdBySignupId(Integer signupId);

    List<Integer> selectCourseIdsBySignupId(Integer id);

    List<SignDetailDO> selectByStuIdAndSignupId(@Param("studentId") Integer studentId,
                                                   @Param("signupId") Integer signupId);

    List<Integer> selectBySignupIdAndCourseId(@Param("signupId") Integer signupId,
                                              @Param("courseId") Integer courseId);

    List<SignDetailDO> selectBySignupId(Integer id);

    void deleteBySignupIdAndStuId(@Param("signupId") Integer signupId,
                                  @Param("studentId") Integer studentId);
}
