package xyz.qzpx.em.dao;

import xyz.qzpx.em.dataObject.TodoListDO;

import java.util.List;

public interface TodoListDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    int insert(TodoListDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    int insertSelective(TodoListDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    TodoListDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    int updateByPrimaryKeySelective(TodoListDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    int updateByPrimaryKey(TodoListDO record);

    List<TodoListDO> selectByUsername(String username);
}
