package xyz.qzpx.em.dataObject;

import java.util.Date;

public class CourseStudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.created_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.updated_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.signup_id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private Integer signupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.course_id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.student_id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.lesson_count
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private Integer lessonCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.registered_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private String registeredAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.end_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private String endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.expense
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private Integer expense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.discount
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private String discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.refund
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private Integer refund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.remark
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.id
     *
     * @return the value of course_student.id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.id
     *
     * @param id the value for course_student.id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.created_at
     *
     * @return the value of course_student.created_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.created_at
     *
     * @param createdAt the value for course_student.created_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.updated_at
     *
     * @return the value of course_student.updated_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.updated_at
     *
     * @param updatedAt the value for course_student.updated_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.signup_id
     *
     * @return the value of course_student.signup_id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public Integer getSignupId() {
        return signupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.signup_id
     *
     * @param signupId the value for course_student.signup_id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setSignupId(Integer signupId) {
        this.signupId = signupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.course_id
     *
     * @return the value of course_student.course_id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.course_id
     *
     * @param courseId the value for course_student.course_id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.student_id
     *
     * @return the value of course_student.student_id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.student_id
     *
     * @param studentId the value for course_student.student_id
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.lesson_count
     *
     * @return the value of course_student.lesson_count
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public Integer getLessonCount() {
        return lessonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.lesson_count
     *
     * @param lessonCount the value for course_student.lesson_count
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setLessonCount(Integer lessonCount) {
        this.lessonCount = lessonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.registered_at
     *
     * @return the value of course_student.registered_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public String getRegisteredAt() {
        return registeredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.registered_at
     *
     * @param registeredAt the value for course_student.registered_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setRegisteredAt(String registeredAt) {
        this.registeredAt = registeredAt == null ? null : registeredAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.end_at
     *
     * @return the value of course_student.end_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public String getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.end_at
     *
     * @param endAt the value for course_student.end_at
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setEndAt(String endAt) {
        this.endAt = endAt == null ? null : endAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.expense
     *
     * @return the value of course_student.expense
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public Integer getExpense() {
        return expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.expense
     *
     * @param expense the value for course_student.expense
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setExpense(Integer expense) {
        this.expense = expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.discount
     *
     * @return the value of course_student.discount
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.discount
     *
     * @param discount the value for course_student.discount
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setDiscount(String discount) {
        this.discount = discount == null ? null : discount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.refund
     *
     * @return the value of course_student.refund
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public Integer getRefund() {
        return refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.refund
     *
     * @param refund the value for course_student.refund
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setRefund(Integer refund) {
        this.refund = refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.remark
     *
     * @return the value of course_student.remark
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.remark
     *
     * @param remark the value for course_student.remark
     *
     * @mbg.generated Tue Apr 07 15:06:20 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}
