package xyz.qzpx.em.dataObject;

public class CourseStudentVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.signup_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Integer signupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.course_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private String courseIds;

    private Integer signdetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_student.student_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.id
     *
     * @return the value of course_student.id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.id
     *
     * @param id the value for course_student.id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.signup_id
     *
     * @return the value of course_student.signup_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Integer getSignupId() {
        return signupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.signup_id
     *
     * @param signupId the value for course_student.signup_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setSignupId(Integer signupId) {
        this.signupId = signupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_student.student_id
     *
     * @return the value of course_student.student_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_student.student_id
     *
     * @param studentId the value for course_student.student_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public String getCourseIds() {
        return courseIds;
    }

    public void setCourseIds(String courseIds) {
        this.courseIds = courseIds;
    }

    public Integer getSigndetailId() {
        return signdetailId;
    }

    public void setSigndetailId(Integer signdetailId) {
        this.signdetailId = signdetailId;
    }
}
