package xyz.qzpx.em.dataObject;

import java.util.Date;

public class CourseDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.created_at
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.updated_at
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.term
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    private String term;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.type
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.grade
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.subject
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.remark
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.created_at
     *
     * @return the value of course.created_at
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.created_at
     *
     * @param createdAt the value for course.created_at
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.updated_at
     *
     * @return the value of course.updated_at
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.updated_at
     *
     * @param updatedAt the value for course.updated_at
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.term
     *
     * @return the value of course.term
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.term
     *
     * @param term the value for course.term
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.type
     *
     * @return the value of course.type
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.type
     *
     * @param type the value for course.type
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.grade
     *
     * @return the value of course.grade
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.grade
     *
     * @param grade the value for course.grade
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.subject
     *
     * @return the value of course.subject
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.subject
     *
     * @param subject the value for course.subject
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.remark
     *
     * @return the value of course.remark
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.remark
     *
     * @param remark the value for course.remark
     *
     * @mbg.generated Wed Mar 18 10:26:41 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}
