package xyz.qzpx.em.dataObject;

import java.util.Date;

public class LessonDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.id
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.created_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.updated_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.at_date
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private Date atDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.begin_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private Date beginAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.end_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private Date endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.outline
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private String outline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.feedback
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private String feedback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.next_outline
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private String nextOutline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.requirement
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private String requirement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.homework
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private String homework;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson.remark
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.id
     *
     * @return the value of lesson.id
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.id
     *
     * @param id the value for lesson.id
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.created_at
     *
     * @return the value of lesson.created_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.created_at
     *
     * @param createdAt the value for lesson.created_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.updated_at
     *
     * @return the value of lesson.updated_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.updated_at
     *
     * @param updatedAt the value for lesson.updated_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.at_date
     *
     * @return the value of lesson.at_date
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public Date getAtDate() {
        return atDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.at_date
     *
     * @param atDate the value for lesson.at_date
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setAtDate(Date atDate) {
        this.atDate = atDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.begin_at
     *
     * @return the value of lesson.begin_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public Date getBeginAt() {
        return beginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.begin_at
     *
     * @param beginAt the value for lesson.begin_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setBeginAt(Date beginAt) {
        this.beginAt = beginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.end_at
     *
     * @return the value of lesson.end_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.end_at
     *
     * @param endAt the value for lesson.end_at
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.outline
     *
     * @return the value of lesson.outline
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public String getOutline() {
        return outline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.outline
     *
     * @param outline the value for lesson.outline
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setOutline(String outline) {
        this.outline = outline == null ? null : outline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.feedback
     *
     * @return the value of lesson.feedback
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.feedback
     *
     * @param feedback the value for lesson.feedback
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.next_outline
     *
     * @return the value of lesson.next_outline
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public String getNextOutline() {
        return nextOutline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.next_outline
     *
     * @param nextOutline the value for lesson.next_outline
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setNextOutline(String nextOutline) {
        this.nextOutline = nextOutline == null ? null : nextOutline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.requirement
     *
     * @return the value of lesson.requirement
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public String getRequirement() {
        return requirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.requirement
     *
     * @param requirement the value for lesson.requirement
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setRequirement(String requirement) {
        this.requirement = requirement == null ? null : requirement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.homework
     *
     * @return the value of lesson.homework
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public String getHomework() {
        return homework;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.homework
     *
     * @param homework the value for lesson.homework
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setHomework(String homework) {
        this.homework = homework == null ? null : homework.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson.remark
     *
     * @return the value of lesson.remark
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson.remark
     *
     * @param remark the value for lesson.remark
     *
     * @mbg.generated Fri Mar 06 11:10:18 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}
