package xyz.qzpx.em.dataObject;

import java.util.List;

public class MenuDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.path
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name_zh
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private String nameZh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.icon_cls
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private String iconCls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.component
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_id
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private Integer parentId;

    private List<MenuDO> children;

    public List<MenuDO> getChildren() {
        return children;
    }

    public void setChildren(List<MenuDO> children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.path
     *
     * @return the value of menu.path
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.path
     *
     * @param path the value for menu.path
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name_zh
     *
     * @return the value of menu.name_zh
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public String getNameZh() {
        return nameZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name_zh
     *
     * @param nameZh the value for menu.name_zh
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setNameZh(String nameZh) {
        this.nameZh = nameZh == null ? null : nameZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.icon_cls
     *
     * @return the value of menu.icon_cls
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public String getIconCls() {
        return iconCls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.icon_cls
     *
     * @param iconCls the value for menu.icon_cls
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setIconCls(String iconCls) {
        this.iconCls = iconCls == null ? null : iconCls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.component
     *
     * @return the value of menu.component
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.component
     *
     * @param component the value for menu.component
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent_id
     *
     * @return the value of menu.parent_id
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent_id
     *
     * @param parentId the value for menu.parent_id
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}
