package xyz.qzpx.em.dataObject;

public class RoleMenuDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.id
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.rid
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.mid
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    private Integer mid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.id
     *
     * @return the value of role_menu.id
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.id
     *
     * @param id the value for role_menu.id
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.rid
     *
     * @return the value of role_menu.rid
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.rid
     *
     * @param rid the value for role_menu.rid
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.mid
     *
     * @return the value of role_menu.mid
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public Integer getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.mid
     *
     * @param mid the value for role_menu.mid
     *
     * @mbg.generated Sun Mar 29 21:13:41 CST 2020
     */
    public void setMid(Integer mid) {
        this.mid = mid;
    }
}