package xyz.qzpx.em.dataObject;

import java.util.Date;

public class ScoreDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.created_at
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.updated_at
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.course_id
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.student_id
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.name
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.exam1
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private Integer exam1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.examM
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private Integer examm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.exam2
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private Integer exam2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.examE
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private Integer exame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.remark
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.created_at
     *
     * @return the value of score.created_at
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.created_at
     *
     * @param createdAt the value for score.created_at
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.updated_at
     *
     * @return the value of score.updated_at
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.updated_at
     *
     * @param updatedAt the value for score.updated_at
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.course_id
     *
     * @return the value of score.course_id
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.course_id
     *
     * @param courseId the value for score.course_id
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.student_id
     *
     * @return the value of score.student_id
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.student_id
     *
     * @param studentId the value for score.student_id
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.name
     *
     * @return the value of score.name
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.name
     *
     * @param name the value for score.name
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.exam1
     *
     * @return the value of score.exam1
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public Integer getExam1() {
        return exam1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.exam1
     *
     * @param exam1 the value for score.exam1
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setExam1(Integer exam1) {
        this.exam1 = exam1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.examM
     *
     * @return the value of score.examM
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public Integer getExamm() {
        return examm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.examM
     *
     * @param examm the value for score.examM
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setExamm(Integer examm) {
        this.examm = examm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.exam2
     *
     * @return the value of score.exam2
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public Integer getExam2() {
        return exam2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.exam2
     *
     * @param exam2 the value for score.exam2
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setExam2(Integer exam2) {
        this.exam2 = exam2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.examE
     *
     * @return the value of score.examE
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public Integer getExame() {
        return exame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.examE
     *
     * @param exame the value for score.examE
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setExame(Integer exame) {
        this.exame = exame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.remark
     *
     * @return the value of score.remark
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.remark
     *
     * @param remark the value for score.remark
     *
     * @mbg.generated Mon Mar 23 15:56:18 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}