package xyz.qzpx.em.dataObject;

public class SignUpDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.id
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.title
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.created_by
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.processing_by
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    private String processingBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.status
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.timeline
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    private String timeline;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.id
     *
     * @return the value of sign_up.id
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.id
     *
     * @param id the value for sign_up.id
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.title
     *
     * @return the value of sign_up.title
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.title
     *
     * @param title the value for sign_up.title
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.created_by
     *
     * @return the value of sign_up.created_by
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.created_by
     *
     * @param createdBy the value for sign_up.created_by
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.processing_by
     *
     * @return the value of sign_up.processing_by
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public String getProcessingBy() {
        return processingBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.processing_by
     *
     * @param processingBy the value for sign_up.processing_by
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public void setProcessingBy(String processingBy) {
        this.processingBy = processingBy == null ? null : processingBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.status
     *
     * @return the value of sign_up.status
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.status
     *
     * @param status the value for sign_up.status
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.timeline
     *
     * @return the value of sign_up.timeline
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public String getTimeline() {
        return timeline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.timeline
     *
     * @param timeline the value for sign_up.timeline
     *
     * @mbg.generated Thu May 07 11:06:57 CST 2020
     */
    public void setTimeline(String timeline) {
        this.timeline = timeline == null ? null : timeline.trim();
    }
}
