package xyz.qzpx.em.dataObject;

public class SignUpDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.id
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.title
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.username
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.status
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.created_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    private String createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.submit1_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    private String submit1At;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.approved1_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    private String approved1At;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.submit2_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    private String submit2At;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_up.approved2_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    private String approved2At;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.id
     *
     * @return the value of sign_up.id
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.id
     *
     * @param id the value for sign_up.id
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.title
     *
     * @return the value of sign_up.title
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.title
     *
     * @param title the value for sign_up.title
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.username
     *
     * @return the value of sign_up.username
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.username
     *
     * @param username the value for sign_up.username
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.status
     *
     * @return the value of sign_up.status
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.status
     *
     * @param status the value for sign_up.status
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.created_at
     *
     * @return the value of sign_up.created_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.created_at
     *
     * @param createdAt the value for sign_up.created_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt == null ? null : createdAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.submit1_at
     *
     * @return the value of sign_up.submit1_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public String getSubmit1At() {
        return submit1At;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.submit1_at
     *
     * @param submit1At the value for sign_up.submit1_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public void setSubmit1At(String submit1At) {
        this.submit1At = submit1At == null ? null : submit1At.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.approved1_at
     *
     * @return the value of sign_up.approved1_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public String getApproved1At() {
        return approved1At;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.approved1_at
     *
     * @param approved1At the value for sign_up.approved1_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public void setApproved1At(String approved1At) {
        this.approved1At = approved1At == null ? null : approved1At.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.submit2_at
     *
     * @return the value of sign_up.submit2_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public String getSubmit2At() {
        return submit2At;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.submit2_at
     *
     * @param submit2At the value for sign_up.submit2_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public void setSubmit2At(String submit2At) {
        this.submit2At = submit2At == null ? null : submit2At.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_up.approved2_at
     *
     * @return the value of sign_up.approved2_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public String getApproved2At() {
        return approved2At;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_up.approved2_at
     *
     * @param approved2At the value for sign_up.approved2_at
     *
     * @mbg.generated Sat Apr 04 22:48:31 CST 2020
     */
    public void setApproved2At(String approved2At) {
        this.approved2At = approved2At == null ? null : approved2At.trim();
    }
}