package xyz.qzpx.em.dataObject;

import java.util.Date;

public class SignDetailDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.created_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.updated_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.signup_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Integer signupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.courses
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private String courses;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.student_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.lesson_count
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Integer lessonCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.registered_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private String registeredAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.end_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private String endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.expense
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Integer expense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.discount
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private String discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.refund
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private Integer refund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sign_detail.remark
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.id
     *
     * @return the value of sign_detail.id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.id
     *
     * @param id the value for sign_detail.id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.created_at
     *
     * @return the value of sign_detail.created_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.created_at
     *
     * @param createdAt the value for sign_detail.created_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.updated_at
     *
     * @return the value of sign_detail.updated_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.updated_at
     *
     * @param updatedAt the value for sign_detail.updated_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.signup_id
     *
     * @return the value of sign_detail.signup_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Integer getSignupId() {
        return signupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.signup_id
     *
     * @param signupId the value for sign_detail.signup_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setSignupId(Integer signupId) {
        this.signupId = signupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.courses
     *
     * @return the value of sign_detail.courses
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public String getCourses() {
        return courses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.courses
     *
     * @param courses the value for sign_detail.courses
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setCourses(String courses) {
        this.courses = courses == null ? null : courses.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.student_id
     *
     * @return the value of sign_detail.student_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.student_id
     *
     * @param studentId the value for sign_detail.student_id
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.lesson_count
     *
     * @return the value of sign_detail.lesson_count
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Integer getLessonCount() {
        return lessonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.lesson_count
     *
     * @param lessonCount the value for sign_detail.lesson_count
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setLessonCount(Integer lessonCount) {
        this.lessonCount = lessonCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.registered_at
     *
     * @return the value of sign_detail.registered_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public String getRegisteredAt() {
        return registeredAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.registered_at
     *
     * @param registeredAt the value for sign_detail.registered_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setRegisteredAt(String registeredAt) {
        this.registeredAt = registeredAt == null ? null : registeredAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.end_at
     *
     * @return the value of sign_detail.end_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public String getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.end_at
     *
     * @param endAt the value for sign_detail.end_at
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setEndAt(String endAt) {
        this.endAt = endAt == null ? null : endAt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.expense
     *
     * @return the value of sign_detail.expense
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Integer getExpense() {
        return expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.expense
     *
     * @param expense the value for sign_detail.expense
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setExpense(Integer expense) {
        this.expense = expense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.discount
     *
     * @return the value of sign_detail.discount
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.discount
     *
     * @param discount the value for sign_detail.discount
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setDiscount(String discount) {
        this.discount = discount == null ? null : discount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.refund
     *
     * @return the value of sign_detail.refund
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public Integer getRefund() {
        return refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.refund
     *
     * @param refund the value for sign_detail.refund
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setRefund(Integer refund) {
        this.refund = refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sign_detail.remark
     *
     * @return the value of sign_detail.remark
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sign_detail.remark
     *
     * @param remark the value for sign_detail.remark
     *
     * @mbg.generated Wed May 20 17:43:08 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}