package xyz.qzpx.em.dataObject;

public class TodoListDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.id
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.username
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.title
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.time
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.status
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.id
     *
     * @return the value of todo_list.id
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.id
     *
     * @param id the value for todo_list.id
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.username
     *
     * @return the value of todo_list.username
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.username
     *
     * @param username the value for todo_list.username
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.title
     *
     * @return the value of todo_list.title
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.title
     *
     * @param title the value for todo_list.title
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.time
     *
     * @return the value of todo_list.time
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.time
     *
     * @param time the value for todo_list.time
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.status
     *
     * @return the value of todo_list.status
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.status
     *
     * @param status the value for todo_list.status
     *
     * @mbg.generated Thu Apr 30 10:33:48 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}